### ISSUE TITLE
Special characters in test name will break the test

### ISSUE THREAD

**Issue by christophrumpel** [JetBrains/pest-intellij#384]
I noticed that some characters like `?` or `=` in the test title will break running the test.

![CleanShot 2022-11-07 at 18 35 53](https://user-images.githubusercontent.com/1394539/200377185-4a11f61f-cc25-4b16-b7c1-5e6ff5671952.png)

Here is the command that PhpStorm tries to run:

`/opt/homebrew/bin/php /Users/christophrumpel/Sites/cr-store/vendor/bin/pest --teamcity /Users/christophrumpel/Sites/cr-store/tests/Feature/Commands/MergeAccountsCommandTest.php "--filter=/^P\\Tests\\Feature\\Commands\\MergeAccountsCommandTest::it\sstops\sif\sat\sleast\sone\saccount\snot\sfound\s=(\swith\s(data\sset\s\".*\"|\(.*\))(\s\/\s(data\sset\s\".*\"|\(.*\)))*(\s#\d+)?)?$/"`

For me, it looks like the special characters break the regex, but @olivernybroe also thought it might be connected to how terminals work.

It is not a big issue, but good to be aware of for now.

**Comment by olivernybroe** [comment]
I have fixed this in main branch now :) 

The issue with `=` sign seems to be a pest/phpunit bug, so I have opened a ticket about that https://github.com/pestphp/pest/issues/643

**Comment by Floppy012** [comment]
This bug still appears when using `+`

**Comment by olivernybroe** [comment]
I have crossposted this to youtrack instead 
https://youtrack.jetbrains.com/issue/WI-76532/Pest-Cant-run-single-test-which-contains-a-sign
