### ISSUE TITLE
"Preferred Coverage Engine" not respected

### ISSUE THREAD

**Issue by nuernbergerA** [JetBrains/pest-intellij#398]
Hey @olivernybroe 

i have tried to set PCov as preferred coverage engine like so
![image](https://user-images.githubusercontent.com/13331388/211619818-64a67006-7186-4873-b8a9-f1a6f98b539d.png)

If i then run with coverage on a folder that i never run before
![image](https://user-images.githubusercontent.com/13331388/211620480-0420f50d-73cc-43d2-b128-dabf7625fb74.png)

it still tries to enable xdebug
![image](https://user-images.githubusercontent.com/13331388/211620686-56b038df-d084-45fb-88b8-2931dac88131.png)
![image](https://user-images.githubusercontent.com/13331388/211620846-9f149342-08c5-4cc9-bc42-be9c309f1570.png)

Thanks for your awesome work.

Cheers Adrian

**Comment by olivernybroe** [comment]
@nuernbergerA hmm interesting, does it use the right engine when you change it in the run configuration afterwards?

**Comment by nuernbergerA** [comment]
Yes and no.

If you only change the engine, apply button is still disabled, if you change for example also the interpreter it's possible to save it.

After all this it works.

**Comment by EdieLemoine** [comment]
I'm running into the same thing and found the same workaround, but the option is not being saved to the run configuration files in `.idea` either way. Now my coworkers will each have to either manually apply the same workaround or suffer with the 10x slower xdebug.

**Comment by olivernybroe** [comment]
Yes IntelliJ must have changed the logic of when it detects changes. 

I don't really use pcov myself, so likely not gonna work on fixing this soon, pr's welcome.

**Comment by EdieLemoine** [comment]
I'd love to help out, but I have zero Java and/or Kotlin experience so it won't go smoothly. :)

I think there's an unhandled exception in the `com.pestphp.pest.configuration.PestTestRunConfigurationEditor#validateEngine` method causing the update to not come through. I've swapped the `return` statement for a `throw` and wrapped the logic in a try/catch block and now it does register the change, but it guess that does mean there's an exception being thrown. 

I'm going to have another look at it tonight, but I don't only want to fix this, I also want this setting to be saved to configuration files. I'll look at plugins that do something similar for reference and dive in.

**Comment by olivernybroe** [comment]
@EdieLemoine you are absolutely right, seems like it is logic related to that part that might have changed!
Great catch :) 

I will submit a PR where we just remove this validation on the engine stuff, don't feel like it's needed anyway.

 In regards to your second question, isn't this already doable with this option in the templates?
 
![image](https://user-images.githubusercontent.com/5870441/222164237-f5cc4350-604e-4a5e-a0f9-8e20fc38bab5.png)

**Comment by olivernybroe** [comment]
@nuernbergerA Will release a new version with the fix, would love if you could test it out also :) 
Closing this one as I assume the fix works, if not, I'll reopen.
 
Install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>
[PEST PHP-1.9.2.zip](https://github.com/pestphp/pest-intellij/files/10861917/PEST.PHP-1.9.2.zip)

**Comment by nuernbergerA** [comment]
Hey @olivernybroe 

somehow its still the same as before 1.9.2

**Comment by nuernbergerA** [comment]
![image](https://user-images.githubusercontent.com/13331388/222173601-335ae74a-8d4e-41e7-a4f8-245f57696583.png)
changing 1 or/and 2 will have no effect and "apply" will be disabled

also if i change other fields to force a change and persist it along with the fields it will not persist them.

**Comment by olivernybroe** [comment]
@nuernbergerA hmm, I had it working for a shortwhile, but experiencing the same now also 😅 Thanks for testing.

**Comment by EdieLemoine** [comment]
Same here, sadly. Also, @olivernybroe I am using saved run configurations but there's no entry for the coverage engine in the generated xml file. 

Is there a way I can manually edit the files to have the option persist? I've tried adding `<option name="coverageEngine" value="PCov" />` in `PhpTestInterpreterSettings` but I'm not sure if it works. The option was already being persisted sometimes, but not consistently.

**Comment by isfedorov** [comment]
@nuernbergerA @EdieLemoine Hi folks! Pest plugin is being maintained by PhpStorm team now. We are going to gradually move all the issues from GitHub to [YouTrack](https://youtrack.jetbrains.com/issues/WI) so that YouTrack would be the only source of tickets for us. I've created [WI-75206](https://youtrack.jetbrains.com/issue/WI-75206/Pest-Coverage-engine-from-run-configuration-template-is-reset-in-run-configuration) for this particular problem so you can vote for it to receive further updates about the issue state. If you have any other issues or comments regarding Pest plugin, please report them directly to [YouTrack](https://youtrack.jetbrains.com/newIssue?project=WI). Thank you!
