### ISSUE TITLE
Code-Inspection not working if Laravel app is in sub directory

### ISSUE THREAD

**Issue by hebinet** [JetBrains/pest-intellij#409]
Hello,

I like this plugin because it helps alot when writing PEST tests and I use it in several projects now.

Recently I noticed, that the code inspection is not working propably if the Laravel application is in a sub directory.

I have the following structure in my Git Repo (and PHPStorm project):

- `\backend` with Laravel app
- `\frontend' with VueJS app

I configured everything right within my PEST file I use the following:
`uses(Tests\TestCase::class)->in('Actions', 'Feature', 'Unit');`

but in my Feature test i get no suggestions for methods in my TestCase class.
![image](https://user-images.githubusercontent.com/24890467/217241860-5e4a8924-643c-4ba4-999c-59c255bce47c.png)

But when I open the Laravel app (`\backend` Folder) in a new project the inspection works fine.

I think there is a problem with finding the correct `Pest.php` file and so the plugin uses PHPUnit Testcase as a fallback. 
![image](https://user-images.githubusercontent.com/24890467/217242342-00efe8be-d80f-40e7-a612-2e01a3c7dd46.png)

Even if I mark the `\backend` folder as Source Root it doesn't work.

But I get the correct methods if i declare the `uses(Tests\TestCase::class)` Statement in the Pest test file, but than I can't execute the Test anymore because of an error with already declared uses for this directory.

Hope this helps to fix the error :)

**Comment by olivernybroe** [comment]
Thank you for detailed description. 

This is likely something that should be changed in `PestConfigurationFileParser.kt`. 

Where is your `phpunit.xml` file and composer.json file located, maybe we can try and change the logic to be based on the relative position to them instead.

One of the problems with your setup is that phpstorm itself does not support multiple projects in one project. In your case I think you are fine for almost all features, as your second project is a VueJS app and not a php app.

**Comment by hebinet** [comment]
Thanks for your quick help.

Unfortunatly this hasn't worked :(
I installed it via zip file and after restarting the IDE it reindexed but `$this` is still the PHPUnit test case.

**Comment by olivernybroe** [comment]
@hebinet it might have cached it (the cache on it is different than the indexing cache). 
Try doing changes to the `Pest.php` file, and perhaps even deleting and creating it again to really trigger the recaching, if that still doesn't work I'll do some more local testing.

**Comment by olivernybroe** [comment]
Fair enough, thanks for testing 👍 

I'll do some more local testing and come back to you. 
One question before, what OS?

**Comment by isfedorov** [comment]
@hebinet The pest plugin is being maintained by PhpStorm team now and we are going to gradually move all the tickets from GitHub to [YouTrack](https://youtrack.jetbrains.com/issues/WI) so that YouTrack would be the single source of tickets for us. I've created a dedicated ticket [WI-75198](https://youtrack.jetbrains.com/issue/WI-75198/Pest-plugin-Type-of-this-in-Pest-test-is-inferred-wrong-in-subproject) for this particular problem so you can vote for it to be notified about further changes. If you have any further complaints/comments or bugs in pest plugin, please report them to [YouTrack](https://youtrack.jetbrains.com/newIssue?project=WI) directly. Thank you!
