### ISSUE TITLE
"Run" doesn't do anything

### ISSUE THREAD

**Issue by mnapoli** [JetBrains/pest-intellij#507]
**Describe the bug**
The "Run" button doesn't do anything anymore. I can't figure out what's happening, I'm very confused! I restarted, updated everything, I don't get any error. Any idea what could be wrong? (I've used the plugin successfully before)

**To Reproduce**
1. Open Pest project
2. Click on "Run"
3. Nothing happens

**Expected behavior**
Tests run.

**Screenshots**
https://github.com/JetBrains/pest-intellij/assets/720328/b4fa5249-5c10-47d9-b12f-c70f406bf40a

**Desktop (please complete the following information):**
 - OS: macOS
 - IntelliJ Version: PhpStorm 2023.2.3
 - Plugin Version: 1.12.0

**Comment by mnapoli** [comment]
Yes, I also checked the path is correct:

<img width="1213" alt="Screen-001404" src="https://github.com/JetBrains/pest-intellij/assets/720328/73fb7b77-d06a-41d8-b908-143b7fee1bdd">

**Comment by olivernybroe** [comment]
Oh, you should prob. report this on YouTrack now, as PhpStorm team only reads messages in there :) 
[YouTrack](https://youtrack.jetbrains.com/newIssue?project=WI)

**Comment by mnapoli** [comment]
Oh wow I missed that, that's really cool!

Reported here: https://youtrack.jetbrains.com/issue/WI-74937/Run-with-the-Pest-plugin-doesnt-do-anything
