### ISSUE TITLE
[WSL] - Error passing method name to --filter parameter

### ISSUE THREAD

**Issue by victoralbino** [JetBrains/pest-intellij#508]
### I have the following problem, when running a method test in phpStorm, the pest call changes the --filter parameter.

When running in various ways within phpStorm, all tests work normally.
As in the examples below:

- Using the command ``` sail test ```
![ezgif-2-19d9b7db20](https://github.com/JetBrains/pest-intellij/assets/9063056/1cac7c54-2183-445a-b0a7-2d25ab8ff01b)

- Using the command  ``` sail test `--filter=...```
![ezgif-2-8e2d5a34e2](https://github.com/JetBrains/pest-intellij/assets/9063056/39d031bf-2ac6-45bf-ae8b-df9d5a4a98e0)

- Using PhpStorm
![ezgif-2-5f008e343c](https://github.com/JetBrains/pest-intellij/assets/9063056/1dc8f15f-5f07-4819-80c6-ec3a7a2190cb)

- The problem however occurs when trying to execute a single separate method:
![ezgif-2-43d84bb46f](https://github.com/JetBrains/pest-intellij/assets/9063056/ed1c489e-569a-4df5-a8e9-9ece4c138b34)

Observing the command that was executed inside the container we have the following:
``` php /var/www/html/vendor/pestphp/pest/bin/pest --teamcity --configuration /var/www/html/phpunit.xml /var/www/html/tests/Unit/ExampleTest.php "--filter=/^(P\\)?Tests\\Unit\\ExampleTest::it\sthat\strue\sis\strue(\swith\s(data\sset\s\".*\"|\(.*\))(\s\/\s(data\sset\s\".*\"|\(.*\)))*(\s#\d+)?)?/" ```

This same command, if executed inside the container or through ```sail [comand here...]```, only works if I correct the ```--filter=``` parameter to the correct name of the method.

I've already tried changing the configuration file, but it still keeps passing the wrong method name to the command:
![Group 1125](https://github.com/JetBrains/pest-intellij/assets/9063056/c659d2a4-d275-4421-804c-ef25373c1116)

I really don't know how to fix this situation.

### Desktop
 - OS: [windows 11]
 - IntelliJ Version: [PhpStorm 2023.2.3]
 - Plugin Version [1.12.0]

**Comment by olivernybroe** [comment]
Hey 👋 

First off, IntelliJ is not managing this plugin, which means the issue should be reported on YouTrack instead.
https://youtrack.jetbrains.com/newIssue?project=WI

They are still going through migrating things. 

Secondly, what do you mean it's the wrong test name?
Your test is called `that true is true`, but is an `it` test, which means the test name is prefixed with `it`. 
This can also be seen in your sail example when it prints out the test name.

I agree that something is not working, but it doesn't seem to be because it is getting the wrong test name 👀

**Comment by nutbuzzwoo** [comment]
I also experienced the same issue when trying to execute each test separately.

**Comment by isfedorov** [comment]
@victoralbino @nutbuzzwoo hi folks! I'm trying to reproduce the problem on my end, meanwhile I see that you run test using docker-compose under WSL. Could you please check if the same scenario will work on windows and not under WSL? Or try to install latest PhpStorm 2023.3 Beta 2 and run tests there? I suspect this can be the similar problem as described at https://youtrack.jetbrains.com/issue/WI-73742 but need to play around a bit to be sure

**Comment by isfedorov** [comment]
Ok, so I've reproduced the problem on windows using docker-compose from WSL and it's definitely the same as described at https://youtrack.jetbrains.com/issue/WI-73742 so could you please try to install [PhpStorm 2023.3 Beta 2](https://www.jetbrains.com/phpstorm/nextversion/) and check if you still will experience the issue?

**Comment by victoralbino** [comment]
I tested with these versions:
- [PhpStorm 2023.2.3] - Don`t works
- [PhpStorm 2023.2.4] - Don`t works
- [PhpStorm 2023.3.Beta] - Don`t works

They all generate the same result for --filter

```"--filter=/^(P\\\\)?Tests\\\\Unit\\\\ExampleTest::it\\sthat\\strue\\sis\\strue(\\swith\\s(data\\sset\\s\".*\"|\\(.*\\))(\\s\\/\\s(data\\sset\\s\".*\"|\\(.*\\)))*(\\s#\\d+)?)?/"```

**Comment by isfedorov** [comment]
I've just checked this on latest 2023.3 on windows using Docker from WSL running a single Pest test and it worked just fine so probably those additional steps are not even required. Anyway, if something doesn't work further, please create an issue in [YouTrack](https://youtrack.jetbrains.com/newIssue?project=WI)
