### ISSUE TITLE
``arch()`` is not recognized as Pest test function

### ISSUE THREAD

**Issue by kusab85** [JetBrains/pest-intellij#520]
``arch()`` is not recognized as Pest test. Therefore it can't be fired up form IDE separately via mouse or keyboard shortcut. 

**Screenshots**
=====================
![obraz](https://github.com/JetBrains/pest-intellij/assets/53086618/c2be4f72-6c83-4e6c-bb6c-fff8ee1f905c)

**Desktop:**
=====================
**PhpStorm 2023.3.4**
Build #PS-233.14475.35, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
**Windows 10.0**
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
Non-Bundled Plugins:
  Dummy Text Generator (1.2.0)
  Batch Scripts Support (1.0.13)
  com.intellij.ideolog (222.3.1.0)
  com.intellij.properties (233.11799.172)
  String Manipulation (9.12.0)
  ru.adelf.idea.dotenv (2024.1)
  de.espend.idea.php.annotation (9.4.0)
  com.laravel_idea.plugin (8.1.2.233)

**Comment by olivernybroe** [comment]
@pestretsov was a new release ever created since the merge of https://github.com/JetBrains/pest-intellij/pull/510 ?

**Comment by smirok** [comment]
@olivernybroe Unfortunately, no. #510 and the following changes will be available in PhpStorm 2024.1
