### ISSUE TITLE
Fix version detection with path mapping

### ISSUE THREAD

**Issue by olivernybroe** [JetBrains/pest-intellij#78]
Version detection does not work with path mapping, we should figure out what is wrong and how to fix this.

Current solution is to just disable version detection.

**Comment by isfedorov** [comment]
@olivernybroe I've created an issue in YT that seems to describe the same problem [WI-75105](https://youtrack.jetbrains.com/issue/WI-75105) thus I'd like to close this ticket. Please comment in YouTrack if that ticket differs from this one and we will file a dedicated ticket about particular problem that you mean in this ticket. (please note that particular case with `path mapping` (e.g. remote interpreters) implicitly will be covered in that YT ticket as an obvious thing)

**Comment by olivernybroe** [comment]
Awesome! Thanks for starting the migration process 🤩 

Just in case you missed it, all discussion threads were used as feature requests and issues where used for bugs 👍

**Comment by isfedorov** [comment]
@olivernybroe Thank you for pointing this out! we will carefully move every ticket/thread discussion to the YouTrack
